### ISSUE TITLE
크롬익스텐션에서 User 세션 정보 연동

### ISSUE THREAD

**Issue by taejinseok** [woowacourse-teams/2020-taggle#154]
# 크롬익스텐션에서 User 세션 정보 연동

## description
 클라이언트 화면 (브라우저)에서 로그인 성공후 JSESSION을 발급받고 해당 쿠키 값을 통해 서버에서 사용자를 식별하고 있습니다. 
하지만 크롬익스텐션은 브라우저와는 별개의 클라이언트로 현재 JSESSION 쿠키값을 가져오지 못하고 있습니다. 

즉, 현재는 크롬익스텐션을 통한 북마크, 태그를 저장하지 못합니다. 브라우저에서 발급받은 JSESSION 쿠키값을 크롬익스텐션에 전달 하여 크롬 익스텐션에서도 성공적으로 저장, 삭제기능을 수행 할 수 있도록 해야 합니다.

## progress
- [ ] 브라우저를 통해 로그인 후, 발급 받은 JSESSION 쿠키 값을 크롬익스텐션에 전달하여 크롬익스텐션에서도 api 호출 할 수 있도록 구현

**Comment by KS-KIM** [comment]
쿠키는 XSS 공격을 통해 탈취당하면 보안상의 문제를 가지게 됨. 쿠키 정보를 직접 가져오지 못하게 httponly flag를 통해 자바스크립트를 통한 접근을 막고 있으므로 다른 해결방안 모색 필요할듯

**Comment by taejinseok** [comment]
지난 해커톤때 httponly 플래그 설정한채로 https에서 쿠키 가져오지 못한다는 거 같이 확인하고서 그걸 그새 잊어버렸음.. 다른 방법 찾아보겠습니다
