### ISSUE TITLE
브라우저에서 로그인한 유저 정보를 크롬 익스텐션으로 가져오기

### ISSUE THREAD

**Issue by taejinseok** [woowacourse-teams/2020-taggle#155]
# 브라우저에서 로그인한 유저 정보를 크롬 익스텐션으로 가져오기

## description
클라이언트 화면 (브라우저)에서 로그인 성공후 JSESSION을 발급받고 해당 쿠키 값을 통해 서버에서 사용자를 식별하고 있습니다.
하지만 크롬익스텐션은 브라우저와는 별개의 클라이언트로 브라우저가 가지고 있는 쿠키를 가져오지 못합니다. 

http flag옵션을 off로 설정한뒤 브라우저의 쿠키를 가져올 수도 있겠지만, xss 공격 등 보안 상의 이유로 쿠키를 통한 값을 가져오는 방법 대신 다른 방법을 통해 크롬 익스텐션으로 유저 정보를 가져와야 합니다.

즉, 현재는 크롬익스텐션을 통한 북마크, 태그를 저장하지 못합니다. 브라우저에서 발급받은 JSESSION 쿠키값을 크롬익스텐션에 전달 하여 크롬 익스텐션에서도 성공적으로 저장, 삭제기능을 수행 할 수 있도록 해야 합니다.

## progress
 - [x] 브라우저가 가지고 있는 유저 정보를 쿠키를 제외한 방법으로 크롬익스텐션에 가져오기

**Comment by KS-KIM** [comment]
https://developer.chrome.com/extensions/tut_oauth#set_up
chrome identity api라는 것을 extension에서 지원하는 것 같은데, 카카오 로그인 API는 불가능하더라도 구글 로그인은 가능하지 않을까 싶음. 자세한건 문서를 더 읽어봐야 알듯.
