### ISSUE TITLE
태그 검색 기능 구현

### ISSUE THREAD

**Issue by ksy90101** [woowacourse-teams/2020-taggle#160]
# 태그를 검색 기능 구현

## description
vuex에 있는 categories를 이용하게 태그 검색 기능 구현

## progress
- [x] 태그를 검색 기능 구현

**Comment by taejinseok** [comment]
현재 카테고리 목록, 그 이하 태그들을 vuex를 통한 상태관리를 하고 있기때문에 vuex의 getter를 활용하면 api를 활용하지 않아도 될 듯 합니다.
