### ISSUE TITLE
검색엔진 최적화를 위한 메타태그 설정

### ISSUE THREAD

**Issue by ksy90101** [woowacourse-teams/2020-taggle#180]
# 검색엔진 최적화를 위한 메타태그 설정

## description
검색엔진 최적화를 위한 메타태그 설정

## 참고자료
https://vue-meta.nuxtjs.org/
https://yamoo9.gitbook.io/vue-a11y-seo/seo (edited) 

## progress
- [x] 검색엔진 최적화를 위한 메타태그 설정

**Comment by KS-KIM** [comment]
vue-meta는 추후 변경하는것을 고려. 현재는 index.html 정적 페이지에 수동으로 설정하여 적용함
