### ISSUE TITLE
기본 북마크 제공 (서비스 사용법)

### ISSUE THREAD

**Issue by taejinseok** [woowacourse-teams/2020-taggle#226]
# 기본 북마크 제공 (서비스 사용법)

## description
- 현재 Taggle 서비스 사용 방법에 대한 가이드가 없다. 서비스 사용방법이 소개된 노션 url을 기본 북마크로 등록하여 서비스 이용자들에게 사용법을 안내 할수 있도록 한다.

## progress
- [ ] 모든 사용자들에게 서비스 사용법이 소개된 페이지를 기본 북마크로 제공한다.

**Comment by KS-KIM** [comment]
#256과 중복이슈. 처리 방법을 다이얼로그로 변경하므로 이슈 닫습니다.
