### ISSUE TITLE
intellij 이슈 기반으로 브랜치 생성하기

### ISSUE THREAD

**Issue by KS-KIM** [woowacourse-teams/2020-taggle#41]
## 설명
이슈 기반으로 브랜치를 생성하면 작업 단위가 분명해지고, 브랜치명 정하는데 고민하지 않을 수 있다.

## 해야할 일
- [ ] 이슈 기반으로 브랜치를 관리할지 결정한다.

**Comment by taejinseok** [comment]
매력적인 제안이다. 팀과 논의 결정후 이슈를 종료한다.
