### ISSUE TITLE
모든 Entity들 column 속성 내 세부 설정 추가

### ISSUE THREAD

**Issue by taejinseok** [woowacourse-teams/2020-taggle#43]
# 모든 Entity들 column 속성 내 세부 설정 추가

## description
현재 Entity Class내부 Column 애노테이션에 nullable, length등의 속성들을 설정하지 않았습니다. 모든 팀원들과 논의 후 각 도메인 컬럼 속성을 정의할 필요가 있습니다. 
## progress
- [x] Entity 클래스의 Column 속성 세부 설정 추가
- [x] DB 명명규칙 정하기

**Comment by KS-KIM** [comment]
현재 기본적으로 필요한 속성은 설정됨
