### ISSUE TITLE
RDBMS 연동하기

### ISSUE THREAD

**Issue by KS-KIM** [woowacourse-teams/2020-taggle#56]
# RDBMS 연동하기

## description
배포된 서버에 RDBMS를 연동하고, production properties를 수정하여 백엔드에 DB를 연결한다.

## progress
- [ ] AWS에 RDBMS 생성
- [ ] RDBMS 서버에 연결
- [ ] properties 수정하여 백엔드와 DB 연결

**Comment by taejinseok** [comment]
Duplicate of #109
