### ISSUE TITLE
Chrome Extension에서 create 메서드의 location 리팩토링

### ISSUE THREAD

**Issue by ksy90101** [woowacourse-teams/2020-taggle#81]
# Chrome Extension에서 create 메서드의 location 리팩토링

## description
Chrome Extension에서 create 메서드의 location에서 id를 추출하지 말고 Location URI를 직접 사용하여 get을 호출하도록 리팩토링.

## progress
- [ ] 리팩토링 작업

**Comment by taejinseok** [comment]
해당 이슈는 location header의 url을 사용하는 대신 create 응답 body의 id를 추출하는 방법을 사용하는 정책으로 변경했다. 따라서 close한다.
